version: "3.9"

services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - work_test_2_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      timeout: 3s
      retries: 10
      interval: 3s
    networks:
      - my_network_2

  api:
    image: vladimirbodrin/test_work:test2
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - my_network_2

volumes:
  work_test_2_pg_data:

networks:
  my_network_2:
    driver: bridge